apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: wildboar.nginx.con
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wildboar.nginx.con
  template:
    metadata:
      labels:
        app: wildboar.nginx.con
    spec:
      containers:
      - name: wildboar-nginx-pod
        image: wildboar.nginx:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: wildboar-nginx-service
spec:
  type: LoadBalancer
  selector:
    app: wildboar.nginx.con
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

