version: '3.8'

services:
        notes:
                build:
                        context: .
                        ports:
                        - 8080:8080
                        - 9229:9229
                        environment:
                        - SERVER-PORT=8080
                        - DATABASE_CONNECTIONSTRING=mongodb://mongo:27017/notes
                        volumes:
                        - ./:/codes
                        command: npm run debug
        mongo:
                image: mongo:4.2.8
                ports:
                - 27017:27017
                volumes:
                - mongodb: /data/db
                - mongo_config: /data/configdb
        volumes:
                mongo:
                mongo_config:  
