FROM debian:buster
RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install nginx mariadb-server apache2 php7.3 libapache2-mod-php7.3 \ 
php7.3-{common,xmlrpc,soap,intl,cli,curl,fpm,mysql,mbstring,zip,gd,xml,pear,gettext,cgi} 

