# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wildboarlb.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lchantel <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2020/11/30 16:44:53 by lchantel          #+#    #+#              #
#    Updated: 2020/12/03 15:42:21 by lchantel         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: core/v1
kind: ConfigMap
metadata:
    namespace: metallb-system
    name: config
data:
    config: |
        address-pools:
        - name: default
          protocol: layer2
          addresses:
          - 192.168.1.100-192.168.1.200

       
