apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wildboar-phpmyadmin-claim
  labels:
    app: phpmyadmin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
