apiVersion: v1
kind: Service
metadata:
  name: wildboar-phpmyadmin-service
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  externalTrafficPolicy: Cluster 
  selector:
    app: phpmyadmin
  ports: 
  - name: phpmyadmin
    port: 5000
    targetPort: 5000
    protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildboar-phpmyadmin-deploy
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      restartPolicy: Always
      containers:
        - name: wildboar-phpmyadmin-pod
          image: wildboar.phpmyadmin:latest
          ports:
            - containerPort: 5000
              name: phpmyadmin
          env:
            - name: PMA_HOST
              value: wildboar-mysql-service
            - name: PMA_PORT
              value: "3306"
          imagePullPolicy: Never
#          volumeMounts:
#            - name: phpmyadmin-persist-storage
#              mountPath: /var/lib/mysql/
#      volumes:
#        - name: phpmyadmin-persist-storage
#          persistentVolumeClaim:
#            claimName: pv-claim-mysql
