apiVersion: v1
kind: Service
metadata:
  name: wildboar-ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  ports:
    - protocol: TCP
      port: 21
      targetPort: 21
      name: ftps
  selector:
    app: ftps 
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  externalTrafficPolicy: Cluster

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildboar-ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
        - name: wildboar-ftps-pod
          image: alpine:latest
          ports:
            - containerPort: 21
              name: ftps
          imagePullPolicy: Never
          volumeMounts:
            - name: wildboar-ftps-start
              mountPath: /docker-entrypoint-ftps
      volumes:
        - name: wildboar-ftps-start
          configMap:
            name: ftps-build

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: ftps-build    
data:
  build.sh: |
    #!/bin/sh
  
    apk update && apk -U -a upgrade
    apk add vsftpd
    rc-update add vsftpd default
    rc-service vsftpd restart
