apiVersion: v1
kind: Service
metadata:
  name: wildboar-grafana-service
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  externalTrafficPolicy: Cluster 
  selector:
    app: grafana 
  ports: 
  - name: grafana
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildboar-grafana-deploy
  labels:
    app: grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      restartPolicy: Always
      containers:
        - name: wildboar-grafana-pod
          image: wildboar.grafana:latest
          ports:
            - containerPort: 3000
              name: grafana
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: wildboar-grafana-secret
                  key: grafana.user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wildboar-grafana-secret
                  key: grafana.password
          imagePullPolicy: Never
---
apiVersion: v1
kind: Secret
metadata:
  name: wildboar-grafana-secret
  labels:
    app: grafana
type: Opaque
stringData:
  grafana.user: wildboar
  grafana.password: wildboar

