apiVersion: v1
kind: Service
metadata:
  name: wildboar-mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
      protocol: TCP
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildboar-mysql-deploy
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
        - name: wildboar-mysql-pod
          image: wildboar.mysql:latest
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysqldb-storage
              mountPath: "/var/lib/mysql/"
          imagePullPolicy: Never
      volumes:
        - name: mysqldb-storage
          persistentVolumeClaim:
            claimName: pv-claim-mysql
