apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  storageClassName: manual
  capacity:
    storage: 500mb
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/lchantel/pv_proj/

---

apiVersion: v1
kind: PersistentVolumeClaim
matadata:
  name: pv-claim-mysql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    request:
      storage: 500mb
